POST http://127.0.0.1:8080/pets
Content-Type: application/json

{
  "id": 150,
  "userId": 2,
  "inAdoption": true,
  "name": "csdacsa",
  "type": "dog",
  "gender": "female",
  "breed": "pitbull",
  "castrated": false,
  "medHistId": "cdsacasd",
  "imgId": "csdcasaw"
}

###
POST http://127.0.0.1:8080/users
Content-Type: application/json

{
  "id": 123,
  "name": "John Doe",
  "dni": "12345678A",
  "email": "johndoe@example.com",
  "password": "secretpassword",
  "phone": "1234567890",
  "imgprofile": "profile.jpg"
}

###
POST http://127.0.0.1:8080/adoptionrequests
Content-Type: application/json

{
  "requestingUserId": 9,
  "petId": 2
}

###
PUT http://127.0.0.1:8080/pets/2/adoption/true

###
GET http://127.0.0.1:8080/pets/bybreed/labrador
###
GET http://127.0.0.1:8080/pets/bybreed/lab
###
GET http://127.0.0.1:8080/adoptionrequests/exist/2/9